#!/bin/bash
yum update -y

# Install Git
yum install -y git

# Install Node.js
curl -fsSL https://rpm.nodesource.com/setup_20.x | bash -
yum install -y nodejs

# Install PM2
npm install -g pm2

# Clone Repo
cd /opt
git clone https://github.com/shaikmohammadrafi77/cloudsecurity.git

# Backend Setup
cd /opt/cloudsecurity/backend
npm install

# Frontend Setup
cd /opt/cloudsecurity/frontend
npm install

# Start Backend
cd /opt/cloudsecurity/backend
pm2 start server.js --name backend

# Build Frontend
cd /opt/cloudsecurity/frontend
npm run build

# Start Frontend
pm2 start "npm start" --name frontend

# Save PM2
pm2 save
pm2 startup
