%%{init: {'theme': 'neutral'}}%%
flowchart TB
    subgraph Client
        B[Browser]
    end

    subgraph Web
        N[Next.js Frontend]
        X[Express API]
    end

    subgraph Data
        M[(MongoDB)]
        S[(AWS S3)]
    end

    subgraph Services
        SMTP[SMTP Server]
    end

    B --> N
    N --> X
    X --> M
    X --> S
    X --> SMTP
