%%{init: {'theme': 'neutral'}}%%
flowchart LR
    user((User))
    admin((Admin))

    UC1([Register / Login])
    UC2([Enable 2FA])
    UC3([Upload File])
    UC4([Download File])
    UC5([Create Share Link])
    UC6([View Security Logs])
    UC7([Manage Folders])

    user --> UC1
    user --> UC2
    user --> UC3
    user --> UC4
    user --> UC5
    user --> UC6
    user --> UC7

    admin --> UC6
